# Generated by Django 4.1.7 on 2023-02-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
