# Generated by Django 4.1.7 on 2023-03-01 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0012_alter_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chats.chatroom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
